# Generated by Django 2.1.2 on 2018-11-03 20:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='_description',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='_price',
            new_name='price',
        ),
    ]
